vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        # associations:
        #     uri_prefix: /images/asso
        #     upload_destination: '%kernel.project_dir%/public/images/asso'
        #     namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        lodgings:
            uri_prefix: /images/lodgings
            upload_destination: '%kernel.project_dir%/public/images/lodgings'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        assos:
            uri_prefix: /images/asso
            upload_destination: '%kernel.project_dir%/public/images/asso'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer