vich_uploader:
    db_driver: orm

# metadata:
#         type: attribute

#         mappings:
#         Association:
#             uri_prefix: /images/Association
#             upload_destination: '%kernel.project_dir%/public/images/Association'
#             namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
#         lodging:
#             uri_prefix: /images/lodging
#             upload_destination: '%kernel.project_dir%/public/images/lodging'
#             namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

